// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for parami_nft
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-11-10, STEPS: `2`, REPEAT: 50, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/parami
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=parami_nft
// --extrinsic=*
// --steps=2
// --repeat=50
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/nft/src/weights.rs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for parami_nft.
pub trait WeightInfo {
    fn back() -> Weight;
    fn mint(n: u32, s: u32, ) -> Weight;
    fn claim() -> Weight;
}

/// Weights for parami_nft using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    // Storage: Did DidOf (r:1 w:0)
    // Storage: Did Metadata (r:1 w:0)
    // Storage: System Account (r:1 w:1)
    // Storage: Nft Deposit (r:1 w:1)
    // Storage: Nft Deposits (r:1 w:1)
    fn back() -> Weight {
        (49_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    // Storage: Did DidOf (r:1 w:0)
    // Storage: Did Metadata (r:1 w:1)
    // Storage: System Account (r:2 w:2)
    // Storage: OrmlNft NextClassId (r:1 w:1)
    // Storage: OrmlNft NextTokenId (r:1 w:1)
    // Storage: Assets Asset (r:2 w:2)
    // Storage: Assets Metadata (r:2 w:2)
    // Storage: Assets Account (r:3 w:3)
    // Storage: Swap Metadata (r:1 w:1)
    // Storage: OrmlNft Classes (r:0 w:1)
    // Storage: OrmlNft Tokens (r:0 w:1)
    // Storage: OrmlNft TokensByOwner (r:0 w:1)
    fn mint(n: u32, _s: u32, ) -> Weight {
        (168_451_000 as Weight)
            // Standard Error: 0
            .saturating_add((12_000 as Weight).saturating_mul(n as Weight))
            .saturating_add(T::DbWeight::get().reads(14 as Weight))
            .saturating_add(T::DbWeight::get().writes(16 as Weight))
    }
    // Storage: Did DidOf (r:1 w:0)
    // Storage: Did Metadata (r:1 w:0)
    // Storage: Nft Deposit (r:1 w:0)
    // Storage: Nft Deposits (r:1 w:1)
    // Storage: Assets Asset (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    fn claim() -> Weight {
        (59_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(7 as Weight))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    // Storage: Did DidOf (r:1 w:0)
    // Storage: Did Metadata (r:1 w:0)
    // Storage: System Account (r:1 w:1)
    // Storage: Nft Deposit (r:1 w:1)
    // Storage: Nft Deposits (r:1 w:1)
    fn back() -> Weight {
        (49_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    // Storage: Did DidOf (r:1 w:0)
    // Storage: Did Metadata (r:1 w:1)
    // Storage: System Account (r:2 w:2)
    // Storage: OrmlNft NextClassId (r:1 w:1)
    // Storage: OrmlNft NextTokenId (r:1 w:1)
    // Storage: Assets Asset (r:2 w:2)
    // Storage: Assets Metadata (r:2 w:2)
    // Storage: Assets Account (r:3 w:3)
    // Storage: Swap Metadata (r:1 w:1)
    // Storage: OrmlNft Classes (r:0 w:1)
    // Storage: OrmlNft Tokens (r:0 w:1)
    // Storage: OrmlNft TokensByOwner (r:0 w:1)
    fn mint(n: u32, _s: u32, ) -> Weight {
        (168_451_000 as Weight)
            // Standard Error: 0
            .saturating_add((12_000 as Weight).saturating_mul(n as Weight))
            .saturating_add(RocksDbWeight::get().reads(14 as Weight))
            .saturating_add(RocksDbWeight::get().writes(16 as Weight))
    }
    // Storage: Did DidOf (r:1 w:0)
    // Storage: Did Metadata (r:1 w:0)
    // Storage: Nft Deposit (r:1 w:0)
    // Storage: Nft Deposits (r:1 w:1)
    // Storage: Assets Asset (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    fn claim() -> Weight {
        (59_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(7 as Weight))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
    }
}
