comment:
  require_changes: true

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        target: 79%
        threshold: 5%
    patch:
      default:
        target: 79%
        threshold: 3%
        if_not_found: failure
        if_ci_failed: error

ignore:
  - "nodes"
  - "runtimes"
