[workspace]
members = [
    'nodes/dana',
    'nodes/para',
    'pallets/*',
    'primitives',
    'runtimes/dana',
    'runtimes/para',
]

[profile.dev]

[profile.release]
panic = 'unwind'
incremental = true
debug = 0

[profile.test]

[profile.bench]
panic = 'unwind'
incremental = true
debug = 0
