// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for parami_swap
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-06-09, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/parami
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=parami_swap
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/swap/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for parami_swap.
pub trait WeightInfo {
    fn create() -> Weight;
    fn add_liquidity() -> Weight;
    fn remove_liquidity() -> Weight;
    fn buy_tokens() -> Weight;
    fn sell_tokens() -> Weight;
    fn sell_currency() -> Weight;
    fn buy_currency() -> Weight;
}

/// Weights for parami_swap using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    // Storage: Swap Metadata (r:1 w:1)
    fn create() -> Weight {
        (12_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    // Storage: Swap Metadata (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Assets Asset (r:1 w:1)
    // Storage: Swap NextTokenId (r:1 w:1)
    // Storage: Swap Provider (r:1 w:1)
    // Storage: Swap Account (r:0 w:1)
    // Storage: Swap Liquidity (r:0 w:1)
    fn add_liquidity() -> Weight {
        (75_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(7 as Weight))
            .saturating_add(T::DbWeight::get().writes(9 as Weight))
    }
    // Storage: Swap Liquidity (r:1 w:1)
    // Storage: Swap Metadata (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Swap Provider (r:1 w:1)
    // Storage: Assets Asset (r:1 w:1)
    // Storage: Swap Account (r:0 w:1)
    fn remove_liquidity() -> Weight {
        (76_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(7 as Weight))
            .saturating_add(T::DbWeight::get().writes(8 as Weight))
    }
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Assets Asset (r:1 w:1)
    fn buy_tokens() -> Weight {
        (68_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
    }
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Assets Asset (r:1 w:1)
    fn sell_tokens() -> Weight {
        (68_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
    }
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Assets Asset (r:1 w:1)
    fn sell_currency() -> Weight {
        (63_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
    }
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Assets Asset (r:1 w:1)
    fn buy_currency() -> Weight {
        (66_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    // Storage: Swap Metadata (r:1 w:1)
    fn create() -> Weight {
        (12_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
    }
    // Storage: Swap Metadata (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Assets Asset (r:1 w:1)
    // Storage: Swap NextTokenId (r:1 w:1)
    // Storage: Swap Provider (r:1 w:1)
    // Storage: Swap Account (r:0 w:1)
    // Storage: Swap Liquidity (r:0 w:1)
    fn add_liquidity() -> Weight {
        (75_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(7 as Weight))
            .saturating_add(RocksDbWeight::get().writes(9 as Weight))
    }
    // Storage: Swap Liquidity (r:1 w:1)
    // Storage: Swap Metadata (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Swap Provider (r:1 w:1)
    // Storage: Assets Asset (r:1 w:1)
    // Storage: Swap Account (r:0 w:1)
    fn remove_liquidity() -> Weight {
        (76_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(7 as Weight))
            .saturating_add(RocksDbWeight::get().writes(8 as Weight))
    }
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Assets Asset (r:1 w:1)
    fn buy_tokens() -> Weight {
        (68_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
    }
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Assets Asset (r:1 w:1)
    fn sell_tokens() -> Weight {
        (68_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
    }
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Assets Asset (r:1 w:1)
    fn sell_currency() -> Weight {
        (63_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
    }
    // Storage: System Account (r:1 w:1)
    // Storage: Assets Account (r:2 w:2)
    // Storage: Assets Asset (r:1 w:1)
    fn buy_currency() -> Weight {
        (66_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
    }
}
