name: Actions

on:
  push:
    branches:
      - main
      - rel/*
    tags:
      - r*
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
      - rel/*
    paths-ignore:
      - "**/*.md"

jobs:
  ru-build:
    uses: ./.github/workflows/build.yml
  ru-test:
    uses: ./.github/workflows/coverage.yml
    needs:
      - ru-build
  ru-release:
    uses: ./.github/workflows/release.yml
    if: startsWith(github.ref, 'refs/tags/r')
    needs:
      - ru-build
      - ru-test
