name: Build

on: workflow_call

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTC_WRAPPER: sccache
  SCCACHE_CACHE_SIZE: 2G

jobs:
  build:
    strategy:
      matrix:
        os: [linux]
        arch: [x86_64, aarch64]

    runs-on: ["self-hosted", "${{ matrix.os }}", "${{ matrix.arch }}"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: rcache
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: ~/.cache/sccache
          key: scache-${{ matrix.os }}-${{ matrix.arch }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            scache-${{ matrix.os }}-${{ matrix.arch }}-

      - name: Install sccache
        env:
          SCCACHE_VERSION: v0.3.0
        run: |
          SCCACHE_FILE=sccache-$SCCACHE_VERSION-${{ matrix.arch }}-unknown-linux-musl
          mkdir -p $HOME/.local/bin
          curl -L "https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          chmod +x $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          sccache --stop-server || true
          sccache --start-server

      - name: Install toolchain
        run: |
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly

          cargo install --locked --force cargo-binstall

          cargo binstall --no-confirm cargo-sweep

      - name: Build Release
        run: cargo build --release --locked

      - name: Post-build
        run: |
          mkdir -p ./out/
          cp ./target/release/parami ./out/parami-${{ matrix.os }}-${{ matrix.arch }}
          cp ./target/release/wbuild/parami-dana-runtime/parami_dana_runtime.compact.compressed.wasm ./out/
          cp ./target/release/parami-collator ./out/parami-collator-${{ matrix.os }}-${{ matrix.arch }}
          cp ./target/release/wbuild/parami-para-runtime/parami_para_runtime.compact.compressed.wasm ./out/

          strip ./out/parami-${{ matrix.os }}-${{ matrix.arch }}
          strip ./out/parami-collator-${{ matrix.os }}-${{ matrix.arch }}

          cargo sweep --time 30

      - name: Stop sccache
        run: sccache --stop-server || true
        if: always()

      - uses: actions/upload-artifact@v3
        with:
          name: parami-${{ matrix.os }}-${{ matrix.arch }}
          path: ./out/parami-${{ matrix.os }}-${{ matrix.arch }}
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: parami-dana-runtime
          path: ./out/parami_dana_runtime.compact.compressed.wasm
          if-no-files-found: error
        if: matrix.arch == 'x86_64' && matrix.os == 'linux'

      - uses: actions/upload-artifact@v3
        with:
          name: parami-collator-${{ matrix.os }}-${{ matrix.arch }}
          path: ./out/parami-collator-${{ matrix.os }}-${{ matrix.arch }}
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: parami-para-runtime
          path: ./out/parami_para_runtime.compact.compressed.wasm
          if-no-files-found: error
        if: matrix.arch == 'x86_64' && matrix.os == 'linux'
